Update read me file
IFRCGo/alert-hub-web-app pull request #115
Opened 2024-05-07 06:26 UTC by barshathakuri

## Addresses:
- #114 

## Changes
- Add read me

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-05-08 06:08 UTC, samshara requested changes

2024-05-08 06:08 UTC, samshara commented on README.md
> +- [ ] Contact
Let's remove this section.

2024-05-08 06:08 UTC, samshara commented on README.md
> +            └── index.tsx (Defines root layout and requests fetched for DomainContext)
This doesn't seem to be out directory structure. Let's use actual directory structure.

2024-05-08 06:16 UTC, samshara commented on README.md
Also, a nice resource to learn about the README.md file and its usage and how to write one.
https://github.com/hackergrrl/art-of-readme

2024-05-13 08:45 UTC, AdityaKhatri approved these changes

2024-05-13 09:15 UTC, samshara submitted a review, later dismissed

2024-05-13 09:15 UTC, samshara commented on .github/ISSUE_TEMPLATE/bug-report---staging.md
> +*Is it critical that this ticket is resolved urgently (e.g. is it a Blocker)?  What is the impact if no change is made?*
Do we have staging environment? If not maybe we don't need this.

2024-05-13 09:15 UTC, samshara commented on APIDOC.md
Let's rename this to APIDOCS.md

2024-05-13 09:15 UTC, samshara commented on APIDOC.md
> +* Go to the [alert-hub-backend](https://github.com/IFRCGo/alert-hub-backend) repository and download the [schema.graphql](https://github.com/IFRCGo/alert-hub-backend/blob/develop/schema.graphql) file
```suggestion
* Go to the [alert-hub-backend](https://github.com/IFRCGo/alert-hub-backend) repository and download the [schema.graphql](https://github.com/IFRCGo/alert-hub-backend/blob/develop/schema.graphql) file.
```

2024-05-13 09:15 UTC, samshara commented on APIDOC.md
> +*Note: The schema file might change in the future. Make sure to use the latest one*
Let's move this to a new line.

2024-05-13 09:15 UTC, samshara commented on APIDOC.md
> +![image](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/a575a073f6aa81839c739a20a.png)
Why are we doing this long process to get the URL. Shouldn't we just have listed down the URL?

2024-05-13 12:57 UTC, frozenhelium approved these changes

2024-05-13 13:00 UTC, merged