Add translations
IFRCGo/alert-hub-web-app pull request #132
Opened 2024-06-21 10:31 UTC by frozenhelium

2024-06-21 11:28 UTC, tnagorra requested changes, later dismissed

2024-06-21 11:28 UTC, tnagorra commented on src/views/RootLayout/index.tsx
> +                        setLanguagePending(true);
When do we set language pending to false.

2024-06-21 11:28 UTC, tnagorra commented on src/views/RootLayout/index.tsx
> +            languageRequestTimeoutRef.current = window.setTimeout(
Is this for debouncing?

2024-06-21 11:28 UTC, tnagorra commented on src/views/RootLayout/index.tsx
> +        setStrings(stringMap);
Doesn't this replace the existing mapping?

2024-06-24 06:20 UTC, barshathakuri approved these changes

2024-06-24 07:51 UTC, merged