Add login page
IFRCGo/alert-hub-web-app pull request #155
Opened 2024-10-18 11:07 UTC by roshni73

## Addresses:
- XXX

## Changes
- Add login page

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-10-29 09:09 UTC, AdityaKhatri requested changes

2024-10-29 09:09 UTC, AdityaKhatri commented on src/views/Login/index.tsx
> +                });
This should be done after the request is submitted. Let me know if a call is necessary.

2024-10-29 09:09 UTC, AdityaKhatri commented on src/views/Login/index.tsx
> +];
We don't need 2 users.

2024-10-29 09:09 UTC, AdityaKhatri commented on src/utils/domain/user.ts
> +}
I think we can take it from server. If the server doesn't have the type right now, add a TODO here.

2024-10-29 09:09 UTC, AdityaKhatri commented on src/views/Login/index.tsx
> +        expires: '2024-12-31T23:59:59Z',
This should follow the user type defined in domain

2024-10-29 09:09 UTC, AdityaKhatri commented on src/views/Login/index.tsx
> +    };
setCaptchaToken can be directly set in the input

2024-10-29 09:09 UTC, AdityaKhatri commented on src/views/Login/index.tsx
> +                        sitekey="10000000-ffff-ffff-ffff-000000000001"
fetch this from environment.

2024-10-30 04:21 UTC, barshathakuri commented on src/components/Navbar/index.tsx
> +                    </Button> */}
Please remove unwanted comments.

2024-10-30 04:21 UTC, barshathakuri commented on src/views/Login/i18n.json
> +        "loginEmailUsername":"Email/Username",
Use only Email
```suggestion
        "loginEmailUsername":"Email/Username",
```

2024-10-30 04:21 UTC, barshathakuri commented on src/views/Login/i18n.json
> +        "loginForgotUserPass":"Forgot your password/username?",
We are only using email
```suggestion
        "loginForgotUserPass":"Forgot your password?",
```

2024-10-30 04:21 UTC, barshathakuri commented on src/views/Login/index.tsx
> +        username: {
```suggestion
        email: {
```

2024-10-30 04:21 UTC, barshathakuri commented on src/views/Login/index.tsx
> +                    username: selectedUser.username,
Remove all username
```suggestion
                    username: selectedUser.username,
```

2024-11-08 08:13 UTC, AdityaKhatri approved these changes

2024-11-11 04:47 UTC, barshathakuri approved these changes

2024-11-11 09:10 UTC, merged