Add my subscription page
IFRCGo/alert-hub-web-app pull request #156
Opened 2024-10-23 10:49 UTC by barshathakuri

## Addresses:
- XXX

## Depends on:
- XXX

## Changes
- Add subscription page
- Add subscribe tab
- Add archive tab

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [ ] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [ ] codegen errors

2024-10-24 08:47 UTC, AdityaKhatri requested changes

2024-10-24 08:47 UTC, AdityaKhatri commented on src/App/routes/index.tsx
> +        title: 'My Subscription',
```suggestion
        title: 'My Subscriptions',
```

2024-10-24 08:47 UTC, AdityaKhatri commented on src/App/routes/index.tsx
> +    path: 'subscription',
```suggestion
    path: 'subscriptions',
```

2024-10-24 08:47 UTC, AdityaKhatri commented on src/components/Navbar/i18n.json
> +        "headerMenuMySubscription": "My Subscription",
```suggestion
        "headerMenuMySubscription": "My Subscriptions",
```

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/Home/AlertsMap/index.tsx
> +    const closeModal = () => setModalOpen(false);
use useModalState or useBooleanState

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/Home/AlertsTable/index.tsx
> +    const closeModal = () => setModalOpen(false);
same as before

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/SubscriptionDetail/SubscriptionActions/index.tsx
> +import { MoreOptionsIcon } from '@ifrc-go/icons';
Unnecessary separation of component

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/SubscriptionDetail/index.tsx
> +    data: any;
define data structure of Subscription

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/index.tsx
> +                'North America',
define Subscription data type. Only then create dummy data for that.

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/index.tsx
> +        setData((prevData) => prevData.filter((item) => item.id !== id));
not necessary

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/index.tsx
> +        });
not necessary

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/index.tsx
> +        onArchive: () => handleArchive(value.id),
set it directly, send id from inside the component

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ActiveSubscription/index.tsx
> +                keySelector={(data) => data.id}
never do this

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ArchiveSubscription/SubscriptionDetail/SubscriptionActions/index.tsx
> +import { MoreOptionsIcon } from '@ifrc-go/icons';
unnecessary components

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ArchiveSubscription/SubscriptionDetail/index.tsx
> +import { Container } from '@ifrc-go/ui';
create a single one and reuse in both

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/ArchiveSubscription/SubscriptionDetail/index.tsx
> +    data: any;
send necessary data individually

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/MySubscription/index.tsx
> +    const closeModal = () => setModalOpen(false);
do not do this

2024-10-24 08:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +
create a proper form based on the created subscription data structure

2024-11-07 10:47 UTC, AdityaKhatri requested changes

2024-11-07 10:47 UTC, AdityaKhatri commented on src/App/routes/index.tsx
> +
remove this

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/Home/AlertFilters/index.tsx
> +    variant?: 'map' | 'table';
undo

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/Home/AlertsMap/index.tsx
> +    }] = useBooleanState(false);
rename

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/Home/AlertsTable/index.tsx
> +    }] = useBooleanState(false);
rename

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +  }
all enums here as well, fix indent

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +interface SubscriptionForm {
add TODO to use this from generated after API is complete

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +    frequency: string | undefined;
```suggestion
    frequency: 'daily' | 'weekly' | undefined;
```

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +    };
put this under useMemo

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +        // setStartDateTo,
remove

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +    );
merge these two

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +    const subscriptionCreate = () => {
use useCallback

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +        // setStartDateTo,
do not update this, completely remove

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/MySubscription/index.tsx
> +    }] = useBooleanState(false);
rename

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/MySubscription/index.tsx
> +                        subscription={undefined}
send current subscription

2024-11-07 10:47 UTC, AdityaKhatri commented on src/views/MySubscription/index.tsx
> +    const rendererParams = useCallback((_: string, value: SubscriptionDetail) => ({
use same renderer but different rendererParams

2024-11-08 04:16 UTC, barshathakuri commented on src/views/NewSubscriptionModal/index.tsx
> +  }
There is no AllCountryList in enums.

2024-11-11 10:38 UTC, AdityaKhatri requested changes

2024-11-11 10:38 UTC, AdityaKhatri commented on src/views/MySubscription/SubscriptionTableItem/index.tsx
> +            </div>
put this inside container

2024-11-11 10:38 UTC, AdityaKhatri commented on src/views/NewSubscriptionModal/index.tsx
> +        activeAdmin1,
this is either or

2024-11-12 04:07 UTC, AdityaKhatri approved these changes

2024-11-12 06:04 UTC, merged