Add Registration Page
IFRCGo/alert-hub-web-app pull request #157
Opened 2024-10-24 11:38 UTC by roshni73

## Addresses:
- XXX

## Changes
- Add registration page

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-10-29 09:11 UTC, AdityaKhatri requested changes

2024-10-29 09:11 UTC, AdityaKhatri commented on src/views/Register/index.tsx
> +        loginLink: (
why is this called loginInfo? Shouldn't it be registerInfo?

2024-10-29 09:24 UTC, AdityaKhatri requested changes

2024-10-29 09:24 UTC, AdityaKhatri commented on src/views/Register/index.tsx
> +    nationalSocietyOptions: [
separate these out

2024-10-29 09:24 UTC, AdityaKhatri commented on src/views/Register/index.tsx
> +            },
unnecessary fields

2024-10-29 09:24 UTC, AdityaKhatri commented on src/views/Register/index.tsx
> +                    onChange={() => setFieldValue}
```suggestion
                    onChange={setFieldValue}
```

2024-10-30 04:24 UTC, barshathakuri commented on src/views/Register/index.tsx
> +} from '@togglecorp/toggle-form';
Add toggle form

2024-11-15 06:02 UTC, barshathakuri commented on src/views/Register/index.tsx
> +                        labelSelector={(option: { society_name: string }) => option.society_name}
Add stringIdSelector or add a keyselector.

2024-11-18 04:38 UTC, AdityaKhatri requested changes

2024-11-18 04:38 UTC, AdityaKhatri commented on src/App/routes/index.tsx
> -
You should not remove this

2024-11-18 04:38 UTC, AdityaKhatri commented on src/views/Register/index.tsx
> +                required: true,
@roshni73 , can you confirm if these are required?
Based on what I discussed with @barshathakuri , these are not required.

2024-11-18 10:13 UTC, roshni73 commented on src/views/Register/index.tsx
> +        loginLink: (
because it contains information related to login, specifically a link to the login page.

2024-11-21 11:22 UTC, AdityaKhatri approved these changes

2024-11-21 11:22 UTC, AdityaKhatri commented on src/views/Register/index.tsx
> +                    ok
fix indent

2024-11-21 11:23 UTC, merged