Add RecoverAccountComfirm page
IFRCGo/alert-hub-web-app pull request #165
Opened 2024-11-12 09:38 UTC by roshni73

## Addresses:
- 
## Changes
- Add the RecoverAccoutConfirm page 

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-11-15 06:04 UTC, barshathakuri approved these changes

2024-11-25 08:57 UTC, AdityaKhatri requested changes

2024-11-25 08:57 UTC, AdityaKhatri commented on src/App/redirects/RecoverAccountRedirects.tsx
> +Component.displayName = 'RecoverAccountRedirects';
```suggestion
Component.displayName = 'RecoverAccountRedirect';
```

2024-11-25 08:57 UTC, AdityaKhatri commented on src/App/redirects/RecoverAccountRedirects.tsx
> +    [key: string]: string | undefined;
not necessary

2024-11-25 08:57 UTC, AdityaKhatri commented on src/views/RecoverAccountConfirm/index.tsx
> +    const { userId, resetToken } = useParams<{ userId: string, resetToken: string }>();
```suggestion
    const { userId, resetToken } = useParams<{ userId?: string, resetToken?: string }>();
```

2024-11-25 08:57 UTC, AdityaKhatri commented on src/views/RecoverAccountConfirm/index.tsx
> +                },
check if token and uuid is there or not

2024-11-25 09:24 UTC, merged