Project set up
IFRCGo/alert-hub-web-app pull request #17
Opened 2024-03-18 10:54 UTC by barshathakuri

- Add packages
- Add ifrc-go-icons

2024-03-18 11:05 UTC, AdityaKhatri approved these changes

2024-03-18 11:05 UTC, AdityaKhatri commented on src/App/routes.tsx
> +    componentProps: { name: '' },
Lets name it IFRC Alert Hub

2024-03-18 11:08 UTC, samshara commented on .unimportedrc.json
> +        "#views/*": ["./src/views/*"]
We won't be needing much of these. 
For example, since we are using graphql `generated` alias won't be used. Let's only create aliases when we need them.

2024-03-18 11:08 UTC, samshara commented on index.html
> +        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
we don't require these fonts.

2024-03-18 11:08 UTC, samshara commented on package.json
> +    "version": "7.1.2",
let's use proper version number for alert-hub.

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "prebuild": "yarn initialize:type",
we don't require much of these

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "postinstall": "patch-package"
we don't require all of these. we could only add add js and css lint for now .

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "@tinymce/tinymce-react": "^4.3.0",
Any idea why we are adding this dependency?

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "@togglecorp/toggle-request": "^1.0.0-beta.2",
We should be careful of adding dependencies. Any reason we are adding form libraries here?

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "html-to-image": "^1.11.11",
I don't think we need them. Any reasons to add these dependencies.  Before adding dependencies, it's crucial to evaluate whether they align with the project's requirements. Let's refrain from including dependencies preemptively.

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "papaparse": "^5.4.1",
same as above.

2024-03-18 11:08 UTC, samshara commented on package.json
> +        "sanitize-html": "^2.10.0"
same as above.

2024-03-18 11:12 UTC, roshni73 approved these changes

2024-03-19 09:56 UTC, tnagorra requested changes, later dismissed

2024-03-19 09:56 UTC, tnagorra commented on .unimportedrc.json
> +    ],
We do not need these.

2024-03-19 09:56 UTC, tnagorra commented on .unimportedrc.json
> +        "@sentry/react"
We might not need most of these

2024-03-19 09:56 UTC, tnagorra commented on .unimportedrc.json
> +        "#views/*": ["./src/views/*"]
Do we already have all of these directories?

2024-03-19 09:56 UTC, tnagorra commented on eslint.config.js
> +    ignores: ['src/generated/types.ts'],
Do we have this file?

2024-03-19 09:56 UTC, tnagorra commented on index.html
> +            href=""
```suggestion
            href="#"
```

2024-03-19 09:56 UTC, tnagorra commented on index.html
> +        <!-- link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&family=Montserrat:wght@300;400;600;700&family=OpenSans:wght@300;400;600;70
Let's just remove this

2024-03-19 09:56 UTC, tnagorra commented on package.json
> +        "lint": "yarn lint:js && yarn lint:css && yarn lint:unused && yarn lint:translation",
Do we have translator?

2024-03-19 09:56 UTC, tnagorra commented on package.json
> +        "generate": "graphql-codegen --config codegen.yml && eslint --fix src/generated/types.ts",
Have we already setup graphql?

2024-03-19 09:56 UTC, tnagorra commented on package.json
> +        "sanitize-html": "^2.9.0"
Are we using all of these dependencies already?

2024-03-19 09:56 UTC, tnagorra commented on scripts/translator.js
> +import { isDefined, listToMap, mapToList } from '@togglecorp/fujs';
We should not need this file.

2024-03-19 09:56 UTC, tnagorra commented on tsconfig.json
> +            "#views/*": ["./src/views/*"]
Do we have all of these directories?

2024-03-19 10:06 UTC, barshathakuri commented on package.json
> +        "lint": "yarn lint:js && yarn lint:css && yarn lint:unused && yarn lint:translation",
Yes

2024-03-19 10:06 UTC, barshathakuri commented on package.json
> +        "generate": "graphql-codegen --config codegen.yml && eslint --fix src/generated/types.ts",
Yes

2024-03-19 10:28 UTC, samshara requested changes

2024-03-19 10:28 UTC, samshara commented on .unimportedrc.json
> +    "ignorePatterns": ["**/node_modules/**", "build/**", "**/parked/**"],
Let's remove **/parked/**

2024-03-19 10:28 UTC, samshara commented on .unimportedrc.json
> +        "graphql-request",
Maybe we don't need this

2024-03-19 10:28 UTC, samshara commented on package.json
> +        "sanitize-html": "^2.9.0"
maybe we should remove this

2024-03-19 10:54 UTC, samshara approved these changes

2024-03-19 10:55 UTC, samshara approved these changes

2024-03-19 10:56 UTC, samshara approved these changes

2024-03-19 10:57 UTC, samshara approved these changes

2024-03-19 10:59 UTC, merged