Subscription page integration
IFRCGo/alert-hub-web-app pull request #175
Opened 2024-11-26 09:30 UTC by barshathakuri

## Addresses:
- #156 

## Changes
- Subscription Detail

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-11-26 10:41 UTC, barshathakuri commented
Code added in https://github.com/IFRCGo/alert-hub-web-app/pull/173

2024-11-28 06:36 UTC, AdityaKhatri requested changes

2024-11-28 06:36 UTC, AdityaKhatri commented on src/views/MySubscription/SubscriptionDetail/index.tsx
> +            return {} as DetailsOfSubsQueryVariables;
return undefined

2024-11-28 06:36 UTC, AdityaKhatri commented on src/views/MySubscription/SubscriptionDetail/index.tsx
> +    const variables = useMemo<DetailsOfSubsQueryVariables>(() => {
```suggestion
    const variables = useMemo<DetailsOfSubsQueryVariables | undefined>(() => {
```

2024-11-28 07:55 UTC, merged