Upgrade and clean up packages
IFRCGo/alert-hub-web-app pull request #20
Opened 2024-03-26 08:08 UTC by samshara

2024-03-26 09:36 UTC, subinasr requested changes

2024-03-26 09:36 UTC, subinasr commented on package.json
> +        "preview": "view preview",
Might be wrong, but isn't it:
```suggestion
        "preview": "vite preview",
```

2024-03-26 11:19 UTC, barshathakuri approved these changes

2024-03-27 06:06 UTC, subinasr approved these changes

2024-03-27 06:07 UTC, merged