Add  Alert Table columns
IFRCGo/alert-hub-web-app pull request #21
Opened 2024-03-27 10:20 UTC by roshni73

## Addresses:
- #10 

## Changes
- Add  Alert Table columns event, event category, region, country, admin and view details in the table

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-03-29 04:10 UTC, barshathakuri requested changes

2024-03-29 04:10 UTC, barshathakuri commented on generated/schema.json
Please move generated file to gitignore.

2024-03-29 04:10 UTC, barshathakuri commented on generated/types.ts
Please move generated file to gitignore.

2024-03-29 04:10 UTC, barshathakuri commented on src/utils/domain/CountryLink/index.tsx
> +        >
Add TODO: Add country Link

2024-03-29 04:10 UTC, barshathakuri commented on src/utils/domain/RegionLink/index.tsx
> +            {name}
Add TODO: Add region link

2024-03-29 04:10 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +// `;
Remove comments

2024-03-29 04:10 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +];
Use query data

2024-04-02 05:31 UTC, barshathakuri requested changes

2024-04-02 05:31 UTC, barshathakuri commented on src/views/AlertTable/i18n.json
> +        "allOngoingAlertTitle":"ALL ALERTS ",
```suggestion
        "allOngoingAlertTitle":"All Alerts ",
```
Making it similar to IFRC GO.

2024-04-02 05:31 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +`;
```suggestion
query  AlertType (
   $regionId: ID!,
   $countryId: ID!,
   $alertId: ID!,
    ) {
    public {
      alertInfos {
        items {
          event
          category
        }
      }
      region(pk: $regionId) {
        id
        name
      }
      country(pk: $countryId) {
        id
        name
      }
      admin1s {
        items {
          id
          name
        }
      }
      alert(pk: $alertId) {
        sent
        url
      }
    }
  }
`;
```
Pass the Id in the query.

2024-04-02 05:31 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +    } = useQuery<PublicAlertTypeQuery, PublicAlertTypeQueryVariables>(
```suggestion
    } = useQuery<AlertTypeQuery, AlertTypeQueryVariables>(
```

2024-04-02 05:31 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +} from '#generated/types';
```suggestion
import {
    AlertTypeQuery,
    AlertTypeQueryVariables,
} from '#generated/types';
```

2024-04-05 09:10 UTC, barshathakuri requested changes

2024-04-05 09:10 UTC, barshathakuri commented on codegen.yml
> +>>>>>>> 7246516 (Add  Alert Table columns event, event category, region, country, admin and view details in the table)
Remove this

2024-04-05 09:10 UTC, barshathakuri commented on generated/types.ts
Remove this file

2024-04-05 09:10 UTC, barshathakuri commented on generated/schema.json
Remove this file

2024-04-05 09:10 UTC, barshathakuri commented on types.stub.ts
> +>>>>>>> 7246516 (Add  Alert Table columns event, event category, region, country, admin and view details in the table)
Remove <<<< Head. Please rebase it to develop

2024-04-05 09:10 UTC, barshathakuri commented on vite.config.ts.timestamp-1712217042372-21fcd90e640fb.mjs
Please remove it

2024-04-08 06:30 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +
Fix import errors

2024-04-08 06:30 UTC, barshathakuri commented on src/views/AlertTable/index.tsx
> +                (item) => (item.infos.map((info) => info.event).join(', ')),
Fix type issues.

2024-04-11 03:59 UTC, barshathakuri requested changes

2024-04-11 03:59 UTC, barshathakuri commented on package.json
> +    "name": "alert-hub",
ifrc-alert-hub

2024-04-11 03:59 UTC, barshathakuri commented on src/views/Home/index.tsx
> +                </TabList>
use translations

2024-04-11 04:17 UTC, samshara commented on src/index.tsx
> +    uri: 'http://localhost:8000/graphql/',
Let's use from env

2024-04-11 04:17 UTC, samshara commented on src/views/AlertTable/index.tsx
> +                (item) => item.country.admin1s?.[0]?.name,
Let's concatenate the names for now

2024-04-11 04:17 UTC, samshara commented on src/views/AlertTable/index.tsx
> +                () => 'View Details',
We can use string translations here

2024-04-11 08:53 UTC, barshathakuri approved these changes

2024-04-11 08:53 UTC, barshathakuri approved these changes

2024-04-11 12:36 UTC, merged