Add global filter
IFRCGo/alert-hub-web-app pull request #31
Opened 2024-04-15 08:41 UTC by barshathakuri

## Addresses:

-  https://github.com/IFRCGo/go-web-app/issues/453
## Changes
- Add global filter for table and map

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-04-16 11:41 UTC, tnagorra requested changes

2024-04-16 11:41 UTC, tnagorra commented on src/views/Home/index.tsx
> +    regions: [],
Should we allow multiple countries and multiple regions filter? @thenav56 @frozenhelium @samshara

2024-04-16 11:41 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +const labelSelector = (alert: AlertFilters) => alert?.label;
```suggestion
const keySelector = (alert: AlertFilters) => alert.key;
const labelSelector = (alert: AlertFilters) => alert.label;
```

2024-04-16 11:41 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +const countryKeySelector = (country: CountryType) => country?.id;
```suggestion
const countryKeySelector = (country: CountryType) => country.id;
```

2024-04-17 09:26 UTC, samshara approved these changes

2024-04-17 09:29 UTC, puranban requested changes

2024-04-17 09:29 UTC, puranban commented on src/views/Home/Filters/index.tsx
> +        onChange,
```suggestion
        onValueChange,
```

2024-04-17 09:32 UTC, puranban commented on src/views/Home/index.tsx
> +}`;
```suggestion
const ALERT_ENUMS = gql`
    query AlertEnums {
        enums {
          AlertInfoCertainty {
            key
            label
          }
          AlertInfoUrgency {
            label
            key
          }
          AlertInfoSeverity {
            key
            label
          }
        }
    }
`;
```

2024-04-17 09:49 UTC, tnagorra commented on src/views/Home/index.tsx
> +    regions: [],
@barshathakuri Why was this conversation resolved? Did we change them to single select?

2024-04-22 06:31 UTC, puranban requested changes, later dismissed

2024-04-22 06:31 UTC, puranban commented on src/views/Home/Filters/index.tsx
> +    countries?: NonNullable<CountryListQuery['public']['allCountries']>;
use the type defined above for `countries`, `admin1`

2024-04-22 06:31 UTC, puranban commented on src/views/Home/Filters/index.tsx
> +                name="countries"
```suggestion
                name="country"
```

2024-04-22 12:49 UTC, frozenhelium approved these changes

2024-04-22 13:17 UTC, tnagorra approved these changes

2024-04-22 13:17 UTC, merged