Fix/alert table
IFRCGo/alert-hub-web-app pull request #42
Opened 2024-04-24 10:14 UTC by roshni73

## Addresses:
- XXX

## Changes
-  Add  count of All alerts

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-04-24 10:33 UTC, samshara commented on src/views/Home/AlertsTable/index.tsx
> +    );
Let's use resolveToString function here

2024-04-25 11:01 UTC, barshathakuri approved these changes

2024-04-26 11:31 UTC, samshara requested changes

2024-04-26 11:31 UTC, samshara commented on src/views/Home/AlertsTable/index.tsx
> +        },
Maybe this is not the correct way to order. Let's use the sortState value to create ordering.

2024-04-29 08:06 UTC, samshara requested changes
The code is not working right now. It's causing AlertsTable to crash. Let's fix all the errors.

2024-04-29 08:58 UTC, samshara approved these changes

2024-04-29 08:58 UTC, merged