Fix Link and admin1 detiails
IFRCGo/alert-hub-web-app pull request #62
Opened 2024-04-25 11:12 UTC by roshni73

## Addresses:
-   https://github.com/IFRCGo/alert-hub-web-app/issues/54
-   https://github.com/IFRCGo/alert-hub-web-app/issues/52

## Changes
-  Add Link in all the value which includes url
- Fix admin1 list in the Alert detail page
- 
## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-04-25 11:30 UTC, barshathakuri approved these changes

2024-04-25 12:28 UTC, samshara requested changes
Also, why there are additional commits here? As previously suggested, always create a branch from `develop` branch. Let's not forget this moving forward.

2024-04-25 12:28 UTC, samshara commented on src/views/AlertDetails/AlertInfo/index.tsx
> +                                to={data?.web || ''}
Why empty string here?

2024-04-25 12:28 UTC, samshara commented on src/views/AlertDetails/AlertMetadata/index.tsx
> +                        to={data?.url || ''}
Let's not use empty string?

2024-04-25 12:28 UTC, samshara commented on src/views/AlertDetails/index.tsx
> +                    filteredAlertCount
any reason we fetch `filteredAlertCount` here? This is not used anywhere.

2024-04-26 08:36 UTC, barshathakuri commented on src/views/AlertDetails/AlertInfo/index.tsx
> +                            </Link>
Use isTruthyString

2024-04-26 10:49 UTC, barshathakuri approved these changes

2024-04-26 10:53 UTC, samshara requested changes

2024-04-26 10:53 UTC, samshara commented on src/views/AlertDetails/AlertInfo/index.tsx
> +import { Link } from 'react-router-dom';
Let's use Link from the components folder

2024-04-26 10:53 UTC, samshara commented on src/views/AlertDetails/AlertMetadata/index.tsx
> +import { Link } from 'react-router-dom';
Let's use Link from the components folder.

2024-04-26 11:25 UTC, samshara requested changes

2024-04-26 11:25 UTC, samshara commented on src/views/AlertDetails/AlertInfo/index.tsx
> +                                target="_blank"
Let's remove the line as the Link component adds the target value internally.

2024-04-26 11:25 UTC, samshara commented on src/views/AlertDetails/AlertMetadata/index.tsx
> +                        target="_blank"
Let's remove this line.

2024-04-26 11:46 UTC, samshara approved these changes

2024-04-26 13:08 UTC, barshathakuri approved these changes

2024-04-29 04:47 UTC, samshara requested changes

2024-04-29 04:47 UTC, samshara commented on src/views/AlertDetails/AlertInfo/styles.module.css
> +    }
Now maybe we don't need these classses.

2024-04-29 04:47 UTC, samshara commented on src/views/AlertDetails/AlertMetadata/styles.module.css
> +            }
Maybe we don't need these classes.

2024-04-29 06:52 UTC, barshathakuri approved these changes

2024-04-29 08:36 UTC, barshathakuri approved these changes

2024-04-29 08:58 UTC, samshara approved these changes

2024-04-29 09:09 UTC, merged